In [3]:
import numpy as np

# ========================================
# CREAR MATRICES CON NUMPY
# ========================================

print("=== 1. MATRIZ DESDE LISTA ===")
# Crear matriz desde una lista de listas
matriz_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Matriz 1:\n", matriz_1)
print("Forma:", matriz_1.shape)  # (3, 3)
print("Tipo de dato:", matriz_1.dtype)
print()

print("=== 2. MATRIZ DE CEROS ===")
# Crear matriz llena de ceros
matriz_ceros = np.zeros((3, 4))
print("Matriz de ceros (3x4):\n", matriz_ceros)
print()

print("=== 3. MATRIZ DE UNOS ===")
# Crear matriz llena de unos
matriz_unos = np.ones((2, 5))
print("Matriz de unos (2x5):\n", matriz_unos)
print()

print("=== 4. MATRIZ IDENTIDAD ===")
# Matriz identidad (diagonal principal = 1)
matriz_identidad = np.eye(4)
print("Matriz identidad (4x4):\n", matriz_identidad)
print()

print("=== 5. MATRIZ CON RANGO ===")
# Crear matriz usando arange
matriz_rango = np.arange(1, 13).reshape(3, 4)
print("Matriz con valores 1-12 (3x4):\n", matriz_rango)
print()

print("=== 6. MATRIZ CON VALORES ALEATORIOS ===")
# Matriz con números aleatorios entre 0 y 1
matriz_aleatoria = np.random.rand(3, 3)
print("Matriz aleatoria (3x3):\n", matriz_aleatoria)
print()

# Matriz con números aleatorios enteros
matriz_aleatoria_int = np.random.randint(1, 20, size=(3, 3))
print("Matriz aleatoria entera (1-19):\n", matriz_aleatoria_int)
print()

print("=== 7. MATRIZ CON NÚMEROS ESPACIADOS ===")
# Crear matriz con números espaciados uniformemente
matriz_linspace = np.linspace(0, 10, 12).reshape(3, 4)
print("Matriz con valores de 0 a 10 (3x4):\n", matriz_linspace)
print()

print("=== 8. OPERACIONES CON MATRICES ===")
# Suma
print("Matriz 1:\n", matriz_1)
print("\nMatriz 1 + 10:\n", matriz_1 + 10)

# Multiplicación elemento a elemento
print("\nMatriz 1 * 2:\n", matriz_1 * 2)

# Producto matricial
print("\nProducto matricial (1 x 1^T):\n", np.dot(matriz_1, matriz_1.T))
print()

print("=== 9. ACCEDER A ELEMENTOS ===")
print("Elemento [0, 0]:", matriz_1[0, 0])
print("Primera fila:", matriz_1[0])
print("Primera columna:", matriz_1[:, 0])
print("Submatriz [0:2, 0:2]:\n", matriz_1[0:2, 0:2])


=== 1. MATRIZ DESDE LISTA ===
Matriz 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma: (3, 3)
Tipo de dato: int64

=== 2. MATRIZ DE CEROS ===
Matriz de ceros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

=== 3. MATRIZ DE UNOS ===
Matriz de unos (2x5):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

=== 4. MATRIZ IDENTIDAD ===
Matriz identidad (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

=== 5. MATRIZ CON RANGO ===
Matriz con valores 1-12 (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

=== 6. MATRIZ CON VALORES ALEATORIOS ===
Matriz aleatoria (3x3):
 [[0.19281696 0.32629945 0.11759496]
 [0.26188211 0.46514048 0.34765756]
 [0.27982722 0.51032356 0.57948085]]

Matriz aleatoria entera (1-19):
 [[19 19  6]
 [ 8  9  3]
 [18 16 17]]

=== 7. MATRIZ CON NÚMEROS ESPACIADOS ===
Matriz con valores de 0 a 10 (3x4):
 [[ 0.          0.90909091  1.81818182  2.72727273]
 [ 3.63636364  4.54545455  5.45454545  6.36363636]
 [ 7.27272727  8.18181818  9.09090909 10.        ]]

=== 8. OP

In [2]:
# 1. Simular 10 lecturas de temperatura entre 15°C y 30°C con linspace
import numpy as np
temperaturas = np.linspace(15, 30, 10)

print("Lecturas simuladas de temperatura (°C):\n", temperaturas)

# 2. Crear una matriz identidad para validar referencia (ideal de calibración)
calibracion = np.identity(3)

print("\nMatriz identidad de referencia para sensores:\n", calibracion)

# 3. Generar 5 lecturas aleatorias de humedad entre 40% y 80%
humedad = np.random.randint(40, 81, size=5)

print("\nLecturas aleatorias de humedad (%):\n", humedad)

# 4. Simular 3 series de luminosidad entre 200 y 800 lúmenes
luminosidad = np.random.randint(200, 801, size=(3, 5))

print("\nLecturas de luminosidad en 3 sensores (lúmenes):\n", luminosidad)

# 5. Reestructurar datos de luminosidad para análisis por minuto
luminosidad_lineal = luminosidad.flatten()

print("\nLecturas de luminosidad aplanadas (por minuto):\n", luminosidad_lineal)

# 6. Preparar arreglo para insertar nuevas mediciones
estructura = np.zeros((3, 5))
estructura[:, :] = np.random.randint(100, 500, size=(3, 5))

print("\nEstructura lista para nuevas mediciones (datos aleatorios insertados):\n", estructura)

Lecturas simuladas de temperatura (°C):
 [15.         16.66666667 18.33333333 20.         21.66666667 23.33333333
 25.         26.66666667 28.33333333 30.        ]

Matriz identidad de referencia para sensores:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Lecturas aleatorias de humedad (%):
 [68 61 41 67 43]

Lecturas de luminosidad en 3 sensores (lúmenes):
 [[352 738 414 561 550]
 [501 466 435 613 717]
 [393 273 779 252 706]]

Lecturas de luminosidad aplanadas (por minuto):
 [352 738 414 561 550 501 466 435 613 717 393 273 779 252 706]

Estructura lista para nuevas mediciones (datos aleatorios insertados):
 [[127. 286. 254. 315. 328.]
 [425. 393. 194. 482. 383.]
 [246. 380. 268. 453. 171.]]


In [4]:
import numpy as np

# Crear dos arreglos de numpy del mismo tamaño
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print("arr1:", arr1)
print("arr2:", arr2)
print()

# Suma elemento a elemento
suma = arr1 + arr2
print("Suma:", suma)

# Resta elemento a elemento
resta = arr1 - arr2
print("Resta:", resta)

# Multiplicación elemento a elemento
multiplicacion = arr1 * arr2
print("Multiplicación:", multiplicacion)

# División elemento a elemento
division = arr1 / arr2
print("División:", division)

# También se pueden usar operaciones con escalares
print()
print("arr1 + 5:", arr1 + 5)
print("arr2 * 10:", arr2 * 10)


arr1: [10 20 30 40]
arr2: [1 2 3 4]

Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]

arr1 + 5: [15 25 35 45]
arr2 * 10: [10 20 30 40]
